# Generated by Django 6.0.3 on 2026-03-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0003_prova_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='questoes_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
